---
title: "Basic education level and BP, Tukey results"
author: "Adriana Lääti et al."
date: "`r Sys.Date()`"
output: html_document
---
 

```{r setup, include=FALSE} 

# Load packages
library(pacman)
p_load(here, dplyr)

# Use package "here" to load data sets in a cross-platform (PC, Mac etc.) way:
#
# First, tell where you are right now - i.e. location of the file you are running right now

here::i_am("article2/README.R")

# After that, you can check where the project root is by running "here()"
here()

#  Load the datasets using {here} package
article2tuva_file <- here("data", "tuva_edu.rds")
article2utuva_file <- here("data", "utuva_edu.rds")
article2tuva_utuva_file <- here("data", "tuva_utuva_edu.rds")


tuva <- readRDS(article2tuva_file)
utuva <- readRDS(article2utuva_file)

tuva_utuva <- readRDS(article2tuva_utuva_file)

# Clean up variables
rm(article2tuva_file, article2utuva_file, article2tuva_utuva_file)
 

# Set up necessary general settings
knitr::opts_chunk$set(echo = FALSE)


```
 
<br><br><br>


## Display N number for TUVA data

<br>

```{r n_tuva}

tuva %>% nrow()

tuva_utuva %>% filter(cohort == "1920-born TUVA cohort") %>% nrow()

```

   
 
<br>
<br>
 
## Display N number for UTUVA data

<br>

```{r n_utuva}

utuva %>% nrow()

tuva_utuva %>% filter(cohort == "1940-born UTUVA cohort") %>% nrow() 
 

```

   
 
<br>
<br>




# Basic education groups and SBP in TUVA

<br>
```{r sbp_tuva}
anova_sbp_tuva <- aov(tuva1sbp ~ basic_school.factor3, data = tuva)
summary(anova_sbp_tuva)
TukeyHSD(anova_sbp_tuva)
```
<br><br><br>



# Basic education groups and DBP in TUVA

<br>
```{r dbp_tuva}
anova_dbp_tuva <- aov(tuva1dbp ~ basic_school.factor3, data = tuva)
summary(anova_dbp_tuva)
TukeyHSD(anova_dbp_tuva)
```
<br><br><br>



# Basic education groups and SBP in UTUVA

<br>
```{r sbp_utuva}
anova_sbp_utuva <- aov(utuva1sbp ~ basic_school.factor3, data = utuva)
summary(anova_sbp_utuva)
TukeyHSD(anova_sbp_utuva)
```
<br><br><br>



# Basic education groups and DBP in UTUVA

<br>
```{r dbp_utuva}

utuva %>%
  group_by(basic_school.factor3) %>%
  summarize(
    mean_utuva1dbp = mean(utuva1dbp, na.rm = TRUE),
    sd_utuva1dpd = sd(utuva1dbp, na.rm = TRUE)
  )


anova_dbp_utuva <- aov(utuva1dbp ~ basic_school.factor3, data = utuva)
summary(anova_dbp_utuva)
TukeyHSD(anova_dbp_utuva)

```
<br><br><br>


